dtc_codes = {
    11: "Crankshaft Position Circuit",
    12: "MAF Circuit",
    13: "Engine Temp Circuit ",
    14: "VSS Circuit",
    21: "Ignition Signal Circuit",
    22: "Fuel Pump Circuit",
    23: "Idle Switch",
    24: "Throttle Valve Switch",
    25: "ISC Valve",
    28: "Cooling Fan Circuit",
    31: "ECM",
    32: "EGR Function",
    33: "LH O2 Circuit",
    34: "Knock Sensor Circuit",
    35: "EGR Temp Sensor Circuit",
    36: "EGRC-BPT Valve",
    37: "Knock Sensor Circuit",
    38: "LH Bank Closed Loop (Bank 2)",
    41: "Intake Air Temp Sensor",
    42: "Fuel Temp Sensor Circuit",
    43: "TPS Circuit",
    45: "Injector Leak",
    47: "Crankshaft Position Sensor",
    51: "Injector Circuit",
    53: "RH O2 Circuit",
    54: "AT ECU Signal",
    55: "No Faults",
    63: "No. 6 Misfire",
    64: "No. 5 Misfire",
    65: "No. 4 Misfire",
    66: "No. 3 Misfire",
    67: "No. 2 Misfire",
    68: "No. 1 Misfire",
    71: "Random Misfire",
    72: "TWC Function RH Bank",
    73: "TWC Function LH Bank",
    76: "Fuel Injection System RH Bank",
    77: "Rear Oxygen Sensor Circuit",
    82: "CKP Sensor",
    84: "A/T Diagnosis Communication Line",
    85: "VTC Solenoid Valve Circuit",
    86: "Fuel Injection System Function LH Bank",
    87: "Canister Control Solenoid Valve Circuit",
    91: "Front Oxygen Sensor Heater Circuit RH Bank",
    94: "TCC Solenoid Valve",
    95: "CKP Sensor",
    98: "ECT Sensor",
    101: "Front Oxygen Sensor Heater Circuit LH Bank", 
    103: "PNP Switch Circuit",
    105: "EGR And EGR Canister Control Solenoid Valve Circuit",
    108: "Canister Purge Control Valve Circuit",
}